@extends('dashboard.layouts.app')

@section('content')
<div class="app-title d-flex justify-content-between align-items-center">
    <div>
        <h1><i class="fa fa-line-chart"></i> Waiter Performance & Sales</h1>
        <p>Track orders and revenue generated by each waiter</p>
    </div>
    <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item"><a href="{{ route($role === 'manager' ? 'admin.dashboard' : 'reception.dashboard') }}">Dashboard</a></li>
        <li class="breadcrumb-item">Waiter Sales</li>
    </ul>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="tile shadow-sm border-0" style="border-radius: 15px;">
            <div class="tile-body">
                <form method="GET" action="{{ route('reception.reports.waiter-sales') }}" class="row align-items-end">
                    <div class="col-md-4">
                        <label class="font-weight-bold">Select Date:</label>
                        <input type="date" name="date" class="form-control rounded-pill" value="{{ $selectedDate->format('Y-m-d') }}" onchange="this.form.submit()">
                    </div>
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-primary btn-block rounded-pill">
                            <i class="fa fa-refresh"></i> Refresh
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Summary Cards -->
<div class="row mb-4">
    <div class="col-md-3">
        <div class="widget-small primary coloured-icon">
            <i class="icon fa fa-users fa-3x"></i>
            <div class="info">
                <h4>Active Waiters</h4>
                <p><b>{{ count($waiterSummaries) }}</b></p>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="widget-small info coloured-icon">
            <i class="icon fa fa-shopping-basket fa-3x"></i>
            <div class="info">
                <h4>Total Orders</h4>
                <p><b>{{ collect($waiterSummaries)->sum('order_count') }}</b></p>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="widget-small success coloured-icon">
            <i class="icon fa fa-money fa-3x"></i>
            <div class="info">
                <h4>Total Revenue</h4>
                <p><b>{{ number_format(collect($waiterSummaries)->sum('total_amount'), 0) }} TZS</b></p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="tile shadow-sm border-0" style="border-radius: 15px;">
            <h3 class="tile-title"><i class="fa fa-list-alt text-primary mr-2"></i> Waiter Sales Breakdown ({{ $selectedDate->format('d M, Y') }})</h3>
            <div class="table-responsive">
                <table class="table table-hover table-bordered text-center">
                    <thead class="bg-light">
                        <tr>
                            <th rowspan="2" class="align-middle">Waiter Name</th>
                            <th rowspan="2" class="align-middle">Orders</th>
                            <th colspan="4" class="text-info border-bottom-0">Platforms (Payment Methods)</th>
                            <th colspan="2" class="text-warning border-bottom-0">Categories</th>
                            <th rowspan="2" class="align-middle bg-primary text-white">Total Sales</th>
                            <th rowspan="2" class="align-middle">Action</th>
                        </tr>
                        <tr class="bg-light">
                            <th>Cash</th>
                            <th>Mobile</th>
                            <th>Card</th>
                            <th>Room Charge</th>
                            <th>Food</th>
                            <th>Bar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($waiterSummaries as $s)
                        <tr>
                            <td class="font-weight-bold text-left">
                                <i class="fa fa-user-circle-o text-muted mr-1"></i> {{ $s->name }}
                            </td>
                            <td><span class="badge badge-pill badge-secondary px-3">{{ $s->order_count }}</span></td>
                            <td class="text-muted">{{ number_format($s->platforms['cash'], 0) }}</td>
                            <td class="text-muted">{{ number_format($s->platforms['mobile'], 0) }}</td>
                            <td class="text-muted">{{ number_format($s->platforms['card'], 0) }}</td>
                            <td class="text-muted">{{ number_format($s->platforms['room_charge'], 0) }}</td>
                            <td class="font-weight-bold text-dark">{{ number_format($s->categories['food'], 0) }}</td>
                            <td class="font-weight-bold text-dark">{{ number_format($s->categories['bar'], 0) }}</td>
                            <td class="bg-primary-light font-weight-bold" style="background: rgba(0, 150, 136, 0.05);">
                                {{ number_format($s->total_amount, 0) }} TZS
                            </td>
                            <td>
                                <button type="button" onclick="showWaiterOrders('{{ $s->name }}', '{{ $selectedDate->format('Y-m-d') }}')" class="btn btn-sm btn-outline-info rounded-pill">
                                    <i class="fa fa-eye"></i> View Orders
                                </button>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="9" class="text-center py-5">
                                <div class="text-muted">
                                    <i class="fa fa-folder-open-o fa-4x mb-3"></i>
                                    <p class="h5">No waiter sales recorded for this date.</p>
                                </div>
                            </td>
                        </tr>
                        @endforelse
                    </tbody>
                    @if(count($waiterSummaries) > 0)
                    <tfoot class="bg-dark text-white font-weight-bold">
                        <tr>
                            <td class="text-left">TOTALS</td>
                            <td>{{ collect($waiterSummaries)->sum('order_count') }}</td>
                            <td>{{ number_format(collect($waiterSummaries)->sum(fn($s) => $s->platforms['cash']), 0) }}</td>
                            <td>{{ number_format(collect($waiterSummaries)->sum(fn($s) => $s->platforms['mobile']), 0) }}</td>
                            <td>{{ number_format(collect($waiterSummaries)->sum(fn($s) => $s->platforms['card']), 0) }}</td>
                            <td>{{ number_format(collect($waiterSummaries)->sum(fn($s) => $s->platforms['room_charge']), 0) }}</td>
                            <td>{{ number_format(collect($waiterSummaries)->sum(fn($s) => $s->categories['food']), 0) }}</td>
                            <td>{{ number_format(collect($waiterSummaries)->sum(fn($s) => $s->categories['bar']), 0) }}</td>
                            <td class="bg-primary">{{ number_format(collect($waiterSummaries)->sum('total_amount'), 0) }} TZS</td>
                            <td></td>
                        </tr>
                    </tfoot>
                    @endif
                </table>
            </div>
        </div>
    </div>
</div>

    </div>
</div>

<!-- Waiter Orders Modal -->
<div class="modal fade" id="waiterOrdersModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content border-0 shadow-lg">
            <div class="modal-header bg-light">
                <h5 class="modal-title" id="waiterOrdersModalTitle">Waiter Orders</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body p-0" id="waiterOrdersModalBody">
                <div class="p-5 text-center">
                    <div class="spinner-border text-primary" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                    <p class="mt-2 text-muted">Fetching orders...</p>
                </div>
            </div>
            <div class="modal-footer bg-light">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<style>
    .bg-primary-light {
        color: #009688;
    }
    .table thead th {
        font-size: 12px;
        text-transform: uppercase;
        letter-spacing: 0.5px;
    }
    .tile {
        transition: transform 0.2s;
    }
    .tile:hover {
        transform: translateY(-2px);
    }
</style>

@section('scripts')
<script>
    function showWaiterOrders(waiterName, date) {
        $('#waiterOrdersModalTitle').text('Orders by ' + waiterName + ' (' + date + ')');
        $('#waiterOrdersModalBody').html(`
            <div class="p-5 text-center">
                <div class="fa-3x text-primary"><i class="fa fa-spinner fa-spin"></i></div>
                <p class="mt-2 text-muted">Fetching orders...</p>
            </div>
        `);
        $('#waiterOrdersModal').modal('show');

        // We use the same platform report endpoint but filter by waiter name in the search
        const url = "{{ route('admin.reports.payment-platform-report') }}?platform=cash&report_type=daily&date=" + date + "&search=" + waiterName;
        
        // Actually, we need to create a small controller adjustment or use an existing one that can return transactions for a waiter
        // For now, let's use the Order Monitor but with AJAX support if we can or just fetch the data
        
        // Let's reuse the logic from the payment-platform-report but specifically for this waiter
        const platformUrl = "{{ route('admin.reports.payment-platform-report') }}?platform=all&report_type=daily&date=" + date + "&waiter=" + encodeURIComponent(waiterName);

        fetch(platformUrl, {
            headers: {
                'X-Requested-With': 'XMLHttpRequest'
            }
        })
        .then(response => response.text())
        .then(html => {
            $('#waiterOrdersModalBody').html('<div class="p-3">' + html + '</div>');
        })
        .catch(error => {
            console.error(error);
            $('#waiterOrdersModalBody').html('<div class="p-5 text-center text-danger"><i class="fa fa-exclamation-triangle fa-2x mb-2"></i><p>Failed to load orders.</p></div>');
        });
    }
</script>
@endsection
@endsection
